# Generated by Django 4.2.2 on 2023-06-30 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bishop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('image', models.ImageField(upload_to=None, verbose_name='Фото')),
                ('birth_date', models.DateField(verbose_name='Дата народження')),
                ('name_day', models.CharField(max_length=20, verbose_name='День тезоіменитства')),
                ('tonsure_date', models.DateField(verbose_name='Дата постригу')),
                ('deacon_ordination_date', models.DateField(verbose_name='Дата дияконської хіротонії')),
                ('priest_ordination_date', models.DateField(verbose_name='Дата ієрейської хіротонії')),
                ('bishop_ordination_date', models.DateField(verbose_name='Дата Архієрейської хіротонії')),
                ('secular_education', models.TextField(verbose_name='Світська освіта')),
                ('spiritual_education', models.TextField(verbose_name='Духовна освіта')),
                ('biography', models.TextField(verbose_name='Біографія')),
            ],
        ),
        migrations.CreateModel(
            name='Clergyman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('image', models.ImageField(upload_to='media/', verbose_name='Фото')),
                ('job_title', models.CharField(max_length=200, verbose_name='Духовна посада')),
                ('birth_date', models.DateField(verbose_name='Дата народження')),
                ('deacon_ordination_date', models.DateField(verbose_name='Дияконська хіротонія')),
                ('priest_ordination_date', models.DateField(verbose_name='Ієрейська хіротонія')),
                ('secular_education', models.TextField(verbose_name='Світська освіта')),
                ('spiritual_education', models.TextField(verbose_name='Духовна освіта')),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('main_image', models.ImageField(upload_to='media/', verbose_name='Головне фото')),
                ('address', models.CharField(max_length=255)),
                ('date_of_establishment', models.DateField(verbose_name='Дата заснування')),
                ('history', models.TextField(verbose_name='Історія')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('main_image', models.ImageField(upload_to='media/', verbose_name='Головне фото')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата створення')),
                ('day_of_week_created', models.CharField(choices=[('MONDAY', 'Понеділок'), ('TUESDAY', 'Вівторок'), ('WEDNESDAY', 'Середа'), ('THURSDAY', 'Четвер'), ('FRIDAY', "П'ятниця"), ('SATURDAY', 'Субота'), ('SUNDAY', 'Неділя')], max_length=20, verbose_name='День створення')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/', verbose_name='Відео')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.publication')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Фото')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.publication')),
            ],
        ),
    ]
