# Generated by Django 4.2.2 on 2023-07-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_clergyman_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bishop',
            options={'verbose_name': 'Архієрей', 'verbose_name_plural': 'Архієрей'},
        ),
        migrations.AlterModelOptions(
            name='clergyman',
            options={'verbose_name': 'Духовенство', 'verbose_name_plural': 'Духовенство'},
        ),
        migrations.AlterModelOptions(
            name='parish',
            options={'verbose_name': 'Парафії', 'verbose_name_plural': 'Парафії'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Публікація', 'verbose_name_plural': 'Публікації'},
        ),
    ]
