# Generated by Django 4.2.2 on 2023-07-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_clergyman_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parish',
            options={'verbose_name': 'Парафія', 'verbose_name_plural': 'Парафії'},
        ),
    ]
