# Generated by Django 4.2.2 on 2023-07-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_parishimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationvideo',
            options={'verbose_name': 'Відео публікації', 'verbose_name_plural': 'Відео публікацій'},
        ),
        migrations.AlterField(
            model_name='publicationimage',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.publication', verbose_name='Публікація'),
        ),
        migrations.AlterField(
            model_name='publicationvideo',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.publication', verbose_name='Публікація'),
        ),
    ]
