# Generated by Django 4.2.2 on 2023-07-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_publicationvideo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('saints', models.TextField(verbose_name="Пам'ять яких святих")),
                ('day_parable', models.TextField(verbose_name='Притча дня')),
            ],
            options={
                'verbose_name': 'Календарний день',
                'verbose_name_plural': 'Календарні дні',
            },
        ),
    ]
